# Generated by Django 6.0.3 on 2026-03-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('semester', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('login', 'Вход в систему'), ('view_lecture', 'Просмотр лекции'), ('submit_assignment', 'Сдача задания'), ('miss_deadline', 'Пропуск дедлайна'), ('take_test', 'Прохождение теста')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('avg_assignment_delay', models.FloatField(default=0)),
                ('success_rate_midterms', models.FloatField(default=0)),
                ('days_since_last_login', models.IntegerField(default=0)),
                ('activity_count_last_week', models.IntegerField(default=0)),
                ('missed_deadlines_count', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0)),
                ('risk_level', models.CharField(default='low', max_length=20)),
                ('explanation', models.JSONField(default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
